r"""
Portable installer for the Unity headless worker.

Run this ONCE on each computer (the agent can run it - it only writes files, it
does not need to launch anything). It detects the machine's Unity editor, the
Unity project and the Python interpreter, then writes:

    worker_config.json       machine-specific paths for unity_headless_worker.py
    launch_worker_silent.vbs windowless launcher with real paths baked in
    start_worker_now.bat     double-click to start the worker immediately
    <Startup>\UnityHeadlessWorker.vbs   so it starts at every logon

It deliberately does NOT start the worker itself: the worker must run in the
USER's context, so if this script were run by the agent the worker would inherit
the broken context. After this script, either log off/on, or double-click
start_worker_now.bat.

Usage:
    python setup_worker.py
    python setup_worker.py --unity "<path>\Unity.exe" --project "<proj dir>"
    python setup_worker.py --no-startup          (skip the Startup entry)
"""

import argparse
import glob
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
STARTUP = os.path.join(os.environ.get("APPDATA", ""),
                       r"Microsoft\Windows\Start Menu\Programs\Startup")

VBS_TEMPLATE = """\
' Starts the Unity headless worker with no visible window.
' Generated by setup_worker.py - do not edit by hand, re-run setup_worker.py.
Option Explicit

Dim PY, SCRIPT, HERE, ws
HERE   = "{here}"
PY     = "{pythonw}"
SCRIPT = HERE & "\\unity_headless_worker.py"

Set ws = CreateObject("WScript.Shell")
ws.CurrentDirectory = HERE
ws.Run Chr(34) & PY & Chr(34) & " " & Chr(34) & SCRIPT & Chr(34), 0, False
"""

BAT_TEMPLATE = """\
@echo off
rem Start the Unity headless worker right now, in YOUR context (windowless).
rem This MUST be started by you - if the agent starts it, Unity's build host
rem cannot do its IPC handshake and every headless job fails.
wscript.exe "%~dp0launch_worker_silent.vbs"
echo Worker launch requested.
timeout /t 6 /nobreak >nul
if exist "%~dp0queue\\_heartbeat.txt" (
  echo Running:
  type "%~dp0queue\\_heartbeat.txt"
) else (
  echo No heartbeat yet - check "%~dp0worker.log"
)
pause
"""


def is_unity_project(d):
    return (os.path.isdir(os.path.join(d, "Assets"))
            and os.path.isdir(os.path.join(d, "ProjectSettings")))


def find_unity():
    cands = sorted(glob.glob(r"C:\Program Files\Unity\Hub\Editor\*\Editor\Unity.exe"))
    if cands:
        return cands[-1]
    cands = sorted(glob.glob(r"C:\Program Files\Unity*\Editor\Unity.exe"))
    return cands[-1] if cands else None


def find_project():
    """HERE, its children, its parent and the parent's children."""
    roots = [HERE]
    parent = os.path.dirname(HERE)
    if parent and parent != HERE:
        roots.append(parent)
    for root in roots:
        if is_unity_project(root):
            return root
        for d in sorted(glob.glob(os.path.join(root, "*"))):
            if os.path.isdir(d) and is_unity_project(d):
                return d
    return None


def find_pythonw():
    d = os.path.dirname(sys.executable)
    p = os.path.join(d, "pythonw.exe")
    if os.path.exists(p):
        return p
    p = shutil.which("pythonw")
    if p:
        return p
    return None


def ask(prompt, default):
    try:
        if not sys.stdin or not sys.stdin.isatty():
            return default
        v = input(f"{prompt} [{default or 'none'}]: ").strip()
        return v or default
    except Exception:
        return default


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--unity")
    ap.add_argument("--project")
    ap.add_argument("--pythonw")
    ap.add_argument("--no-startup", action="store_true")
    a = ap.parse_args()

    unity = a.unity or find_unity()
    project = a.project or find_project()
    pythonw = a.pythonw or find_pythonw()

    print("Detected:")
    print(f"  Unity   : {unity or '(not found)'}")
    print(f"  Project : {project or '(not found)'}")
    print(f"  Python  : {pythonw or '(not found)'}")

    if not unity or not os.path.exists(unity):
        unity = ask("Path to Unity.exe", unity)
    if not project or not is_unity_project(project):
        project = ask("Path to the Unity project folder", project)
    if not pythonw or not os.path.exists(pythonw):
        pythonw = ask("Path to pythonw.exe", pythonw)

    problems = []
    if not unity or not os.path.exists(unity):
        problems.append("Unity.exe not found")
    if not project or not is_unity_project(project):
        problems.append("no folder containing Assets\\ and ProjectSettings\\")
    if not pythonw or not os.path.exists(pythonw):
        problems.append("pythonw.exe not found")
    if problems:
        print("\nSETUP INCOMPLETE: " + "; ".join(problems))
        print("Re-run with explicit paths, e.g.:")
        print('  python setup_worker.py --unity "<path>\\Unity.exe" '
              '--project "<path>\\MyProject"')
        return 1

    cfg = {
        "_comment": "Generated by setup_worker.py. Paths are machine-specific - "
                    "regenerate on each computer.",
        "unity": unity,
        "project": project,
        "logdir": os.path.join(project, "Logs", "worker"),
    }
    with open(os.path.join(HERE, "worker_config.json"), "w", encoding="utf-8") as f:
        json.dump(cfg, f, indent=2)
    print("\nWrote worker_config.json")

    vbs = VBS_TEMPLATE.format(here=HERE, pythonw=pythonw)
    vbs_path = os.path.join(HERE, "launch_worker_silent.vbs")
    with open(vbs_path, "w", encoding="utf-8") as f:
        f.write(vbs)
    print("Wrote launch_worker_silent.vbs")

    bat_path = os.path.join(HERE, "start_worker_now.bat")
    with open(bat_path, "w", encoding="utf-8") as f:
        f.write(BAT_TEMPLATE)
    print("Wrote start_worker_now.bat")

    os.makedirs(os.path.join(HERE, "queue"), exist_ok=True)
    os.makedirs(os.path.join(HERE, "queue", "done"), exist_ok=True)
    os.makedirs(cfg["logdir"], exist_ok=True)

    if a.no_startup:
        print("\nStartup entry skipped (--no-startup).")
    elif not os.path.isdir(STARTUP):
        print(f"\nWARNING: Startup folder not found: {STARTUP}")
    else:
        dst = os.path.join(STARTUP, "UnityHeadlessWorker.vbs")
        shutil.copyfile(vbs_path, dst)
        print(f"\nInstalled autostart: {dst}")

    print("\n" + "=" * 62)
    print("SETUP DONE. To activate the worker WITHOUT rebooting, double-click:")
    print(f"    {bat_path}")
    print("(It must be YOU who starts it. After that it starts automatically at")
    print(" every logon, and the agent can run headless Unity jobs on its own.)")
    print("=" * 62)
    return 0


if __name__ == "__main__":
    sys.exit(main())
